### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ubx** [maluethi/meta-glide#5]
- [x] Setup a todo list
- [x] XCSoar: start on boot
- [x] XCSoar: CAN device menu, remove speed setting  (commit 96b126d)
- [ ] XCSoar: investigate map jitter
- [ ] XCSoar: display flap position
- [x] XCSoar: display FLARM/ADBS aircraft
- [ ] XCSoar: CANPort::SetFilter, use enum for filter and switch statement.
- [ ] glide: test on Display L hardware
- [ ] glide: create a maintenance menu (with Qt for Embedded Linux, use fb)
- [ ] glide maintenance menu: upload XCSoar site files
- [ ] glide maintenance menu: update XCSoar 
- [ ] glide maintenance menu: download igc files from vario
- [ ] glide maintenance menu: ??

**Comment by ubx** [comment]
Move to [Port XCSoar to Dysplay-L](https://github.com/ubx/XCSoar/projects/1)
